//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace OnlineShop.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.UsersCards = new HashSet<UsersCard>();
            this.Rating = 3;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quanty { get; set; }
        public string Image { get; set; }
        [Range(1,6)]
        public byte Rating { get; set; }
    
        public virtual ICollection<UsersCard> UsersCards { get; set; }
    }
}
